name: Checks

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  typos:
    name: check misspelling by typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - name: Run typos command
        shell: nix shell nixpkgs#typos --quiet --command bash {0}
        run: |
          typos --hidden --exclude .git \
            --no-check-files ./movies.json \
            --format brief

  cargo-clippy:
    name: lint rust code by clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run cargo clippy
        run: |
          cargo clippy --release -- -D warnings
          cargo clippy --examples --release -- -D warnings
          cargo clippy --tests -- -D warnings

  cargo-doc:
    name: lint rust docstring by rustdoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-docs
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run cargo doc
        run: |
          RUSTDOCFLAGS="-D warnings" cargo doc --no-deps

  cargo-fmt:
    name: check rust formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run cargo fmt
        run: cargo fmt --check
